version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: univesp_pi
      MYSQL_USER: univesp
      MYSQL_PASSWORD: univesp
    ports:
      - 3308:3306
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    command: --init-file /docker-entrypoint-initdb.d/init.sql --local-infile=1
  teste:
    depends_on:
      - mysql
    command: command
# your_mysql_root_password
  # superset:
  #   depends_on:
  #     - mysql
  #   image: apache/superset:latest
  #   restart: always
  #   environment:
  #     - SUPERSET_SECRET_KEY= secret_key
  #     # - DATABASE_URI=mysql://usuario_univesp:usuario_univesp@mysql:3306/univesp_pi
  #   ports:
  #     - 8088:8088

volumes:
  mysql-data:
